version: '2'

services:

 rester-front:
  container_name: rester-front
  image: rester/rester-docker
  restart: always
  volumes:
   - ./nginx-conf:/etc/nginx/sites-available:ro
   - ./cfg:/var/www/cfg:ro
   - ./src:/var/www/src
   - ./lib:/var/www/lib
  ports:
  - '80:80'
